<a href="https://colab.research.google.com/github/bloodfield2/ProyectoVision/blob/main/Proyecto_de_visi%C3%B3n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Proyecto de Visión 
#     Practical Self Calibration Using a Planar Scene
## Estudiantes
Chin Parra Keny

Chávez Aparicio Edgar Iván

##    

#    EN PROGRESO:

Se está probando el código para el caso de un solo par de imágenes para
después extender a N.

#    TODO

##  Para un solo par de imágnes
+ ~Feature Matching~
+ Projective reconstruction
+ Projective Boundle Adjustment 
+ Homography based calibration
+ Netric reconstruction
+ Metric Boundle Adjustment


##  Para N imágnes
+ Feature Matching
+ Projective reconstruction
+ Projective Boundle Adjustment 
+ Homography based calibration
+ Netric reconstruction
+ Metric Boundle Adjustment 

In [3]:
import numpy as np
import cv2 
import glob

MAX_FEATURES = 500
GOOD_MATCH_PERCENT = 0.15

In [4]:
img1 = cv2.imread('/home/Proyecto de visión/picture_2022-03-09_14-10-45.jpg',0)
img2 = cv2.imread('/home/Proyecto de visión/picture_2022-03-09_14-10-49.jpg',0)

In [10]:
def Features(img1,img2):
    # Detect ORB features and com pute descriptors.
    orb = cv2.ORB_create(MAX_FEATURES)
    keypoints1, descriptors1 = orb.detectAndCompute(img1, None)
    keypoints2, descriptors2 = orb.detectAndCompute(img2, None)

    # Match features.
    matcher = cv2.DescriptorMatcher_create(cv2.DESCRIPTOR_MATCHER_BRUTEFORCE_HAMMING)
    matches = matcher.match(descriptors1, descriptors2, None)

    # Sort matches by score
    matches = sorted(matches,key=lambda x: x.distance, reverse=False)

    # Remove not so good matches
    numGoodMatches = int(len(matches) * GOOD_MATCH_PERCENT)
    matches = matches[:numGoodMatches]

    # Extract location of good matches
    points1 = np.zeros((len(matches), 2), dtype=np.float32)
    points2 = np.zeros((len(matches), 2), dtype=np.float32)
    for i, match in enumerate(matches):
        points1[i, :] = keypoints1[match.queryIdx].pt
        points2[i, :] = keypoints2[match.trainIdx].pt
    return points1, points2

In [13]:
# Part 1: Feature Matching
points1, points2 = Features(img1,img2)
print(points1.shape,points2.shape)


(75, 2) (75, 2)


In [16]:
# Part 2: First Proyective resconstruction
h, status = cv2.findHomography(points1, points2)
print(h)

[[ 2.14640029e+00  2.46424939e-01 -1.80895350e+02]
 [ 1.63626100e-01  1.53999084e+00 -1.69429229e+01]
 [ 1.99463699e-03  1.06972742e-04  1.00000000e+00]]
